# Dockerfile-develop
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://mirror.abrha.net/repository/pypi/simple

RUN adduser --disabled-password --gecos "" appuser

RUN mkdir -p /app/staticfiles /app/media && \
    chown -R appuser:appuser /app/staticfiles /app/media

COPY . .
RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

# COPY wait-for-redis.sh /app/wait-for-redis.sh
# RUN chmod +x /app/wait-for-redis.sh