# Dockerfile.offline
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    # تنظیم مسیر برای استفاده از venv
    PATH="/venv/bin:$PATH"

WORKDIR /app

# کپی کل پوشه venv
COPY venv /venv

# تنظیم PYTHONPATH برای استفاده از پکیج‌های venv
ENV PYTHONPATH="/venv/lib/python3.12/site-packages:$PYTHONPATH"

# کپی پروژه
COPY . .

# ایجاد کاربر غیر روت (اختیاری)
RUN adduser --disabled-password --gecos "" appuser && \
    chown -R appuser:appuser /app /venv
USER appuser

EXPOSE 8000

# اجرای جنگو با استفاده از پایتون داخل venv
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
