name: todo app test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Test Django App with Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Run migrations
      run: docker-compose run --rm backendtodo python manage.py migrate --noinput
    
    - name: Run flake8 (Linting)
      run: docker-compose run --rm backendtodo flake8 . --max-line-length=88 --extend-ignore=E203
    
    - name: Run tests with pytest
      run: docker-compose run --rm backendtodo pytest . -v --maxfail=5
    
    - name: Bring down containers
      if: always()  # حتی اگر تست‌ها شکست خوردند، کانتینرها را متوقف کن
      run: docker-compose down