name: todo app test with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Test:
    name: Test Django App with Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker images
      run: docker compose build
    
    - name: Run migrations
      run: docker compose run --rm backendtodo python manage.py migrate
    
    - name: Run flake8
      run: docker compose run --rm backendtodo flake8 . --max-line-length=88 --extend-ignore=E203,W503 --exclude=venv,.venv,migrations
    
    - name: Run tests
      run: docker compose run --rm backendtodo pytest . -v --maxfail=5 --disable-warnings
    
    - name: Cleanup
      if: always()
      run: docker compose down