name: todo app test with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Test with Docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker images
      run: docker-compose build
    
    - name: Run migrations and tests
      run: |
        # ابتدا migrations را اجرا کن (برای ساخت جدول Token)
        docker-compose run --rm backendtodo python manage.py migrate --noinput
        
        # سپس تست‌ها را اجرا کن
        docker-compose run --rm backendtodo pytest . -v --maxfail=5 --disable-warnings
    
    - name: Run flake8
      run: docker-compose run --rm backendtodo flake8 . --max-line-length=88 --extend-ignore=E203,W503 --exclude=venv,.venv,migrations
    
    - name: Clean up
      if: always()
      run: docker-compose down